### ISSUE TITLE
FR1.  Log in Page 

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#1]
|FR1.  Log in Page|
|--|
|**Goal**: The system will give the user a page that the user would log in with their Wayne State University access id so that they could save the schedule under their account.

**Stakeholders: **Computer Science Student|

|**Description:**This would be the first page to show up when the app is opened by the user. This page will prompt user to input his/her Wayne State University access id. After the student have logged in using both his or her access id, the page would greet the user with a selected message with their respective name assigned to their access id. We will be currently only focusing on the students in our class, so the app will only recognize the access id if the students present in our class. We will be using a table that would contain both the information on access id and the name associated with it, which will be referred to when the welcome message would be displayed. Alternate case: When the user fails to put an access id accordingly to the certain and display a pre-selected message asking the user to input the access id in that forms.|

|**Origin: **Based on initial project specification document, team members came up with this description during the second meeting.|

|**Version:** 1.0 | 
|**Date: **01/31/2021 | 
|**Priority**: 1|

**Comment by ryanksz** [comment]
We have one that is displayed when the app runs
