### ISSUE TITLE
FR10.  Search by time UI

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#10]
Goal: To have the user be able to look up what classes are offered on that/ those particular times

Stakeholders: Computer Science Student (User)

After the user has chosen to register for classes from the menu bar, he or she will be directed to this page to register for classes. In the app, the user will be able to search by the time and see what classes are available for that particular semester. Being that students have other obligations rather its being a parent, or having a job this feature will help them make a schedule quickly. For example: this app would help the student register to class giving more consideration to their schedule availability that could be filled with factors such as internships, job or any other commitments.  The app would also use warning message or error message that would help guide the user to use the tools accurately. For example: if there are no time selected, the user would get a message letting them know they need to select a time

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date:  01/31/2021 | Priority: 2

**Comment by ryanksz** [comment]
Search functionality was added to the create schedule page can search by time (or online course)
