### ISSUE TITLE
FR11. Search by Semesters

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#11]
Goal: To help users look up classes by the semester in question.
--
Stakeholders: Computer Science Student

While searching for classes this give the user the option to search for specific classes for the current and future semester, whit allowing the user to do so this will help them plan their schedule accordingly and take what classes are currently available that will not be available in the upcoming future semesters. If a class is not offered an error message will occur stating that no classes are available.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date: 01/31/2021 | Priority: 1

**Comment by ryanksz** [comment]
Search functionality was added to the create schedule page search by the semesters start and end dates
