### ISSUE TITLE
NR6. Reliability

### ISSUE THREAD

**Issue by CiahGreen** [WSU-4110/DegreeScheduler#12]
NR6. Reliability
--
Goal: To have the app unfailing making sure that everything goes smoothly. Making sure that the app is responding in a timely manner, the app is responding correctly.
Stakeholders: Administrators/ Engineers maintaining the system
Making sure the application is dependable for the users. Taking the time to make sure all the features such as buttons work, and the input(s) from the user is getting saved correctly. Making sure the user(s) can access the app without any issues and making it user friendly. The app would also use warning message or error message that would help guide the user to use the tools accurately. For example: if the app is not responding because the user doesn’t have internet connection, it will show a message that says no internet connection, try again.
Origin: Based on initial project specification document, team members came up with this description during the second meeting.
Version: 1.0 | Date:  01/31/2021 | Priority: 1

**Comment by ryanksz** [comment]
All the features in the app work as displayed. We made sure the app is user friendly and intuitive to use. Errors occur if there was issues logging in, no classes are returned if none are found, and the app will say if there is no internet connection. The app is reliable to use and we made sure to fix any bugs that occur.
