### ISSUE TITLE
 FR12.  Search by Major UI

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#13]
Goal: The system will give the user an opportunity to search the classes based on the choice of the major.
--
Stakeholders: Computer Science Student

After the user has chosen to register for classes from the menu bar, he or she will be directed to this page to register for classes. When the student is planning to view his or her schedule, he or she has an option to choose his/her major, which is currently going to only going to focus on the Computer Science major. This could help him/ her choose classes that is intended for that specific major. The app would suggest the classes that is assigned to the chosen major, when it comes for the student registration. The worst-case scenario: In this app we are only focusing on computer science major students, we are assuming that the students in the class are majoring in computer science so the schedule would only show the courses of computer science major.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date: 01/31/2021 | Priority: 1

**Comment by ryanksz** [comment]
Search functionality was added to the create schedule page, can search by the majors' class (math, physics, csc, english and more)
