### ISSUE TITLE
FR13.  Search by Filters UI

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#14]
Goal: To have the user to be able to look up courses based on choosing any combinations of the above options and filtering out the courses they need.
--
Stakeholders: Computer Science Student (User)

After the user has chosen to register for classes from the menu bar, he or she will be directed to this page to register for classes. In the app, the user will be able to search by any combination of the above features. They can be able to generate a list of courses that result from a combination of choosing course name, course number, availability, credits, professors, level, date, time, semesters, and / or major. If no courses are available for a specific combination of filters, an error message will occur stating so and will also ask you to choose another combination of filters or exit.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date: 01/31/2021 | Priority: 2

**Comment by ryanksz** [comment]
Search functionality was added to the create schedule page, the bar on top can search multiple attributes a class may have all in one search bar. The list will then display matching results.
