### ISSUE TITLE
FR15. Download and Share schedule

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#16]
Goal: Allow the user to download and share their schedule.
--
Stakeholders: Computer Science Student

After the user creates their schedule or class list, they can have the option to download and/or share their schedule with others. The user must have a saved schedule to download/share it. The schedule will be a simple format that most others can see.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date: 01/31/2021 | Priority: 6

**Comment by ryanksz** [comment]
We added a way to download the file as a txt file into the user's downloads folder in their phone.
