### ISSUE TITLE
FR16. Contacting students with advice

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#17]
Goal: The counselors would be able to view the email with a copy of the students schedule to give any advice or suggestion regarding it.
--
Stakeholders: Computer Science Faculty

When the computer science students choose to contact the advisor by choosing the contact your advisor from the menu bar. The counselors could use email to clear any doubts or suggest anything that student have that concerns with his/ her respective schedule. Counselor could also choose to view the uploaded schedule, if one is provided by the student. The counselor could also seek the student for the schedule if it is not provided already. Counselor could use this method to see the current plan of that student and help them with any override for a class or update the Ellucian Degree works according to it. It would be an easier way for them to assist the student if the schedule is already provided. Worst case scenario: There be an error in connecting to the outbox to send the email, then we would be sending a pre-selected error message advising the user to close the app and try again.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date: 01/31/2021 | Priority: 1

**Comment by ryanksz** [comment]
A page was added where the users can contact others via their email. The page takes them to the outlook login and they can contact others from their.
