### ISSUE TITLE
NR1. Security

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#19]
Goal: Keep information offline unless user agrees to share.
--
Stakeholders: Administrators/ Engineers maintaining the system

To keep the information secure, the system will not collect or share data to the developers. However, the user can optionally share their schedule. If the user wishes to send their schedule, the schedule will be the only thing sent to another user. All other data is kept offline on the app.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date:  01/31/2021 | Priority:1

**Comment by ryanksz** [comment]
The user can optionally share their schedule via the download/share page. The course information can be kept offline if the user chooses not to share that information.
