### ISSUE TITLE
FR2.  Menu for Navigation UI 

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#2]
|FR2. Menu for Navigation UI|
|--|
|**Goal: The system will give the user a menu bar that would help the user navigate throughout the app.
Stakeholders: Computer Science Student|

|**Description**: After the user is logged in using the Wayne State University access id. The user would be taken into a page where he/ she would have to choose one of the options from the menu bar to navigate throughout the app. This menu bar would have contents like create a new schedule, contact the advisor, view the existing schedule, update the current schedule, and register for classes. After clicking one of the options from the menu bar the user will be directed to a page which is related to the topic of choice from the menu bar. For example: If user clicks the option contact the advisor option from the menu bar then the user will be directed to the outlook that would be used to contact the advisor. Worst case scenario: If the user clicks on the wrong buttons from the menu bar and sent to a different page, he/she will have an option to go back to the menu bar when he/she opens the app again.|

|**Origin**: Based on initial project specification document, team members came up with this description during the second meeting.|

|**Version**: 1.0 |
|**Date:** 01/31/2021 |
|** Priority**: 1|

**Comment by ryanksz** [comment]
Menu is created and can jump to multiple pages in the app. See menu.java.
