### ISSUE TITLE
 NR2. Privacy Policy

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#20]
Goal: To have the user to be able to have access to the privacy policy of this app in order to be better informed of their privacy,
 their rights, what the app shares, reads, and stores, and how it will keep user information safe and secure.
--
Stakeholders: Administrators/ Engineers maintaining the system

When looking at the users’ privacy regarding the app, the personal information recorded during use consists of their grades when updating, their personalized schedules, their search history, and their downloadable / sharable version of their schedules. This information will only be recorded will the app is in use and will not be shared, marketed, or sold to other parties. Regarding the computer science faulty information that will be stored in the app, this information is pulled from the Wayne State’s registrar database, which is already open to the Wayne State Community. Thus, it will also not be shared, marketed, or sold to other parties. The user will be provided with an agreement in which he / she has to agree to first before she can use the app, which essentially outlines the above information and gives consent to the app to store user information.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date:  01/31/2021 | Priority: 1

**Comment by ryanksz** [comment]
Privacy policy was added by Ciah
