### ISSUE TITLE
NR3. Usability

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#23]
Goal: To help the user use the app more comfortably and the features used in the app are simple.  User should be able to successfully learn to operate it, prepare the inputs and comprehend the output.
--
Stakeholders: Administrators/ Engineers maintaining the system

When choosing the theme of the app, we would consider usage of colors that is easier to interpret for the users with color blindness. The system should always keep the users informed about what is going on through appropriate feedback within a reasonable time. The app would be aesthetic and have minimalist design that would contain concise text with relevant text. It will have menu bar that would make navigating through the app easier, and choice box that would be direct and easier to use. The app would also use warning message or error message that would help guide the user to use the tools accurately. For example: There would be a message asking the user for updating the grades after each semester end. Worst case scenario: If the users find the theme to be distracting, having trouble with any feature, or have any feedback on the usability of the app he/she could contact the administrator.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date:  01/31/2021 | Priority: 1

**Comment by ryanksz** [comment]
The app keeps a minimal design with a clear, concise layout. We have a menu bar, messages that pop up when an error occurs, returns nothing if no courses are found, all in a simple easy to follow layout.
