### ISSUE TITLE
 NR4. Availability

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#24]
Goal: Indicate up to which degree the app would be both accessible and operational
--
Stakeholders: Administrators/ Engineers maintaining the system

They need to make sure that the app is available and operational for the user to use it whenever he/she wants. Even though the degree of the availability will vary depended on the system. We must make sure the degree of the availability is 99.99%. The user will not have access to the app when the app undergoes updates to fix any bugs present, without losing any stored information. Worst-case scenario: If the app is facing any trouble like not opening or lost the stored data. Users could feel free to contact the administrators to fix the trouble, and if they have downloaded the schedule they could refer to it to create a new schedule.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date:  01/31/2021 | Priority:1

**Comment by ryanksz** [comment]
The app will maintain stored information in the phone's storage. The user can refer to the information stored at any time. The app is available on any modern android phone. Users can contact us or raise an issue in github and we can release an update.
