### ISSUE TITLE
NR5. Performance

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#25]
Goal: To ensure the server, network and programming are at optimal level.
--
Stakeholders: Administrators/ Engineers maintaining the system

The goal is to make the app as fast and accurate as possible while utilizing as little memory as possible. Although not all user will have a pleasant experience with the app it does not mean that it lacks satisfactory performance. If the app is slow and lagging, they can always contact the administrator and report the bug.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date:  01/31/2021 | Priority:1

**Comment by ryanksz** [comment]
The app works fast, even on emulated android, uses little amount of space and memory.
