### ISSUE TITLE
FR3. Search by Course Name

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#3]
Goal: This will allow the user to search a course by name
--
Stakeholders: Computer Science Student

When the user wants to search for a course, they can simply search up the name of the course they want. If courses are found, they will be displayed to the user, if not nothing will be displayed to the user.  The user can add or view details about each class that appears. Multiple classes can appear based off what the user searched.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date: 01/31/2021 | Priority: 1

**Comment by ryanksz** [comment]
Search functionality was added to the create schedule page to search by course name
