### ISSUE TITLE
FR4. Search by Course Number

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#4]
Goal:  Allow the user to find a course by its number.
--
Stakeholders: Computer Science Student

When a user wants to search for a specific course, they can look it up by the course number. This will allow the user to find the exact course they want. The user can add or view details about the class that appears. The specified class will be the only class that appears. If no class is found, no classes will be showed.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date: 01/31/2021 | Priority: 1

**Comment by ryanksz** [comment]
Search functionality was added to the create schedule page to search by course numbers
