### ISSUE TITLE
FR5. Search by Availability (courses open/ full)

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#5]
Goal: This Will Allow The User To Search For Availability Of The Course.
--
Stakeholders: Computer Science Student

When a user searches for a specific course, this will allow them to only view courses that are open and add it to their schedule accordingly. By displaying only the open courses computer science student would have an easier time scheduling their classes, this would also help avoid scheduling a class that the student can’t register for. If no classes are available an error will occur stating that no classes were found.

Origin: Based on initial project specification document, team members came up with this description during the second meeting.

Version: 1.0 | Date: 01/31/2021 | Priority:4

**Comment by ryanksz** [comment]
This app displays open courses for the user to select. If the class isn't found it won't return any classes.
