### ISSUE TITLE
FR7.  Search by Professor UI

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#7]
Goal: To have the user to be able to look up what they need by professor. Rather it be for a class, or information to contact a professor.

Stakeholders: Computer Science Student (User)

After the user has chosen to register for classes from the menu bar, he or she will be directed to this page to register for classes. In the app, the user will be able to search by professor and see what classes he/she will be teaching for that semester. This would give the user an opportunity to choose courses mentioned in his/her schedule that corresponds to the professor of his/her choice. The app would also use warning message or error message that would help guide the user to use the tools accurately. For example: if the professor is no longer at Wayne State, the user would get a message letting them know that there is no information on that professor, try again.

Origin: Based on initial project specification document, team members produced this description during the second meeting.

Version: 1.0 | Date:  01/31/2021 | Priority: 6

**Comment by ryanksz** [comment]
Search functionality was added to the create schedule page, can search by professors
