### ISSUE TITLE
FR8. Search by Level

### ISSUE THREAD

**Issue by VisshruthaV** [WSU-4110/DegreeScheduler#8]
Goal: To help users search for classes by their current academic level.
--
Stakeholders: Computer Science Student

This option helps the users search for classes offered only to their specific academic level, when speaking about academic level meaning for example some classes are only offered or needed for seniors while others are only offered or needed for freshman's.

Origin: Based on initial project specification document, team members produced this description during the second meeting.

Version: 1.0 | Date: 01/31/2021 | Priority:6

**Comment by ryanksz** [comment]
Search functionality was added to the create schedule page, can search by level (1000, 2000, 3000, 4000, 5000+)
